import 'server-only'

/**
 * Support Email Service
 *
 * Sends the four transactional emails generated by the support system:
 *   1. ticket-created → admin inbox (contact@earn4insights.com)
 *   2. ticket-created → user (confirmation)
 *   3. admin-reply → user
 *   4. user-reply → admin inbox
 *   5. ticket-resolved → user
 *
 * Follows the same `Resend` client + fail-soft pattern as
 * `competitiveEmailService.ts`. If RESEND_API_KEY is unset the call
 * returns `{ success: false }` and logs a warning — never throws,
 * so ticket creation never breaks on email outage.
 */

import { Resend } from 'resend'
import { maskEmail } from '@/lib/logger'
import type { SupportTicket } from '@/db/schema'

const ADMIN_INBOX = process.env.SUPPORT_ADMIN_EMAIL || 'contact@earn4insights.com'

let resend: Resend | null = null
function getResendClient(): Resend | null {
  if (!resend && process.env.RESEND_API_KEY) {
    resend = new Resend(process.env.RESEND_API_KEY)
  }
  return resend
}

function appUrl(): string {
  return process.env.NEXT_PUBLIC_APP_URL || 'https://earn4insights.com'
}

function from(): string {
  return process.env.EMAIL_FROM || 'support@earn4insights.com'
}

type SendResult = { success: boolean; error?: string }

async function send(opts: {
  to: string
  subject: string
  html: string
  text: string
  replyTo?: string
}): Promise<SendResult> {
  if (!process.env.RESEND_API_KEY) {
    console.warn(`[support-email] RESEND_API_KEY not set — skipping ${opts.subject}`)
    return { success: false, error: 'API key not configured' }
  }
  const client = getResendClient()
  if (!client) return { success: false, error: 'Resend client not initialised' }
  try {
    const { error } = await client.emails.send({
      from: from(),
      to: opts.to,
      subject: opts.subject,
      html: opts.html,
      text: opts.text,
      replyTo: opts.replyTo,
    })
    if (error) {
      console.error(`[support-email] send failed to ${maskEmail(opts.to)}:`, error)
      return { success: false, error: String(error) }
    }
    return { success: true }
  } catch (err) {
    console.error(`[support-email] send threw for ${maskEmail(opts.to)}:`, err)
    return { success: false, error: err instanceof Error ? err.message : String(err) }
  }
}

// ── Shared chrome ────────────────────────────────────────────────

function emailShell(title: string, body: string): string {
  return `<!DOCTYPE html>
<html><head><meta charset="utf-8"/><style>
  body { font-family: -apple-system, system-ui, sans-serif; background: #f6f7fb; margin: 0; padding: 24px; color: #1f2937; }
  .card { max-width: 600px; margin: 0 auto; background: #fff; border-radius: 10px; overflow: hidden; box-shadow: 0 1px 4px rgba(0,0,0,0.04); }
  .header { padding: 20px 24px; background: linear-gradient(135deg, #4f46e5 0%, #7c3aed 100%); color: #fff; font-weight: 600; font-size: 16px; }
  .body { padding: 24px; line-height: 1.6; font-size: 14px; }
  .meta { background: #f9fafb; padding: 12px 16px; border-radius: 6px; margin: 12px 0; font-size: 13px; }
  .meta strong { display: inline-block; min-width: 90px; color: #4b5563; }
  .button { display: inline-block; padding: 10px 18px; background: #4f46e5; color: #fff !important; text-decoration: none; border-radius: 6px; margin-top: 8px; font-weight: 500; }
  .quote { border-left: 3px solid #e5e7eb; padding: 6px 14px; margin: 14px 0; color: #4b5563; white-space: pre-wrap; }
  .footer { padding: 16px 24px; font-size: 12px; color: #6b7280; text-align: center; }
  .badge { display: inline-block; padding: 2px 8px; border-radius: 12px; font-size: 11px; font-weight: 600; text-transform: uppercase; letter-spacing: 0.04em; }
  .badge-high { background: #fef2f2; color: #b91c1c; }
  .badge-urgent { background: #fee2e2; color: #991b1b; }
  .badge-medium { background: #fef3c7; color: #92400e; }
  .badge-low { background: #ecfdf5; color: #065f46; }
</style></head>
<body><div class="card">
  <div class="header">${title}</div>
  <div class="body">${body}</div>
  <div class="footer">Earn4Insights — The Intelligence Operating System for Brands, Consumers and Influencers</div>
</div></body></html>`
}

function priorityBadge(priority: SupportTicket['priority']): string {
  return `<span class="badge badge-${priority}">${priority}</span>`
}

function escapeHtml(s: string): string {
  return s
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
    .replace(/'/g, '&#39;')
}

function truncate(s: string, n: number): string {
  if (s.length <= n) return s
  return s.slice(0, n - 1).trimEnd() + '…'
}

// ════════════════════════════════════════════════════════════════
// 1. New ticket → admin inbox
// ════════════════════════════════════════════════════════════════

export async function sendTicketCreatedToAdmin(params: {
  ticket: SupportTicket
  userName: string
}): Promise<SendResult> {
  const { ticket, userName } = params
  const url = `${appUrl()}/admin/support/tickets/${ticket.id}`
  const subject = `[${ticket.ticketNumber}] New support ticket: ${ticket.subject}`
  const body = `
    <p>A new support ticket has been opened.</p>
    <div class="meta">
      <p><strong>Ticket:</strong> ${ticket.ticketNumber}</p>
      <p><strong>From:</strong> ${escapeHtml(userName)} (${escapeHtml(ticket.userEmail)})</p>
      <p><strong>Role:</strong> ${escapeHtml(ticket.userRole)}</p>
      <p><strong>Category:</strong> ${escapeHtml(ticket.category)}</p>
      <p><strong>Priority:</strong> ${priorityBadge(ticket.priority)}</p>
    </div>
    <p><strong>Subject:</strong> ${escapeHtml(ticket.subject)}</p>
    <div class="quote">${escapeHtml(truncate(ticket.description, 500))}</div>
    <p><a class="button" href="${url}">View ticket in admin</a></p>
  `
  const text = `New ticket ${ticket.ticketNumber}: ${ticket.subject}
From: ${userName} (${ticket.userEmail}) — ${ticket.userRole}
Category: ${ticket.category}  Priority: ${ticket.priority}

${truncate(ticket.description, 500)}

View: ${url}`
  return send({ to: ADMIN_INBOX, subject, html: emailShell('New support ticket', body), text })
}

// ════════════════════════════════════════════════════════════════
// 2. New ticket → user (confirmation)
// ════════════════════════════════════════════════════════════════

export async function sendTicketCreatedToUser(params: {
  ticket: SupportTicket
  userName: string
}): Promise<SendResult> {
  const { ticket, userName } = params
  const url = `${appUrl()}/support/tickets/${ticket.id}`
  const subject = `We received your request — ${ticket.ticketNumber}`
  const body = `
    <p>Hi ${escapeHtml(userName || 'there')},</p>
    <p>Thanks for getting in touch. We've received your support ticket and our team will respond within 24 hours.</p>
    <div class="meta">
      <p><strong>Ticket:</strong> ${ticket.ticketNumber}</p>
      <p><strong>Subject:</strong> ${escapeHtml(ticket.subject)}</p>
      <p><strong>Category:</strong> ${escapeHtml(ticket.category)}</p>
    </div>
    <p>You can view the ticket and any replies from your dashboard:</p>
    <p><a class="button" href="${url}">View ticket</a></p>
    <p style="color: #6b7280; font-size: 13px;">If your question is urgent or about a specific charge, replying to this email or adding a reply on the ticket will reach our team faster.</p>
  `
  const text = `Hi ${userName || 'there'},

We've received your support ticket ${ticket.ticketNumber}: ${ticket.subject}
Our team will respond within 24 hours.

View: ${url}`
  return send({
    to: ticket.userEmail,
    subject,
    html: emailShell(`Ticket ${ticket.ticketNumber} received`, body),
    text,
    replyTo: ADMIN_INBOX,
  })
}

// ════════════════════════════════════════════════════════════════
// 3. Admin reply → user
// ════════════════════════════════════════════════════════════════

export async function sendAdminReplyToUser(params: {
  ticket: SupportTicket
  userName: string
  message: string
}): Promise<SendResult> {
  const { ticket, userName, message } = params
  const url = `${appUrl()}/support/tickets/${ticket.id}`
  const subject = `Update on your ticket ${ticket.ticketNumber}`
  const body = `
    <p>Hi ${escapeHtml(userName || 'there')},</p>
    <p>Our team has replied to your ticket <strong>${ticket.ticketNumber}</strong>:</p>
    <div class="quote">${escapeHtml(message)}</div>
    <p><a class="button" href="${url}">View full conversation</a></p>
    <p style="color: #6b7280; font-size: 13px;">Reply to this email to continue the conversation.</p>
  `
  const text = `Hi ${userName || 'there'},

Our team has replied to your ticket ${ticket.ticketNumber}:

${message}

View: ${url}`
  return send({
    to: ticket.userEmail,
    subject,
    html: emailShell(`Update on ticket ${ticket.ticketNumber}`, body),
    text,
    replyTo: ADMIN_INBOX,
  })
}

// ════════════════════════════════════════════════════════════════
// 4. User reply → admin inbox
// ════════════════════════════════════════════════════════════════

export async function sendUserReplyToAdmin(params: {
  ticket: SupportTicket
  userName: string
  message: string
}): Promise<SendResult> {
  const { ticket, userName, message } = params
  const url = `${appUrl()}/admin/support/tickets/${ticket.id}`
  const subject = `Re: [${ticket.ticketNumber}] ${ticket.subject}`
  const body = `
    <p>${escapeHtml(userName)} replied to ticket <strong>${ticket.ticketNumber}</strong>.</p>
    <div class="meta">
      <p><strong>Ticket:</strong> ${ticket.ticketNumber}</p>
      <p><strong>From:</strong> ${escapeHtml(userName)} (${escapeHtml(ticket.userEmail)})</p>
      <p><strong>Status:</strong> ${escapeHtml(ticket.status)}</p>
    </div>
    <div class="quote">${escapeHtml(message)}</div>
    <p><a class="button" href="${url}">View in admin</a></p>
  `
  const text = `${userName} replied to ${ticket.ticketNumber}:

${message}

View: ${url}`
  return send({ to: ADMIN_INBOX, subject, html: emailShell('User replied', body), text })
}

// ════════════════════════════════════════════════════════════════
// 5. Ticket resolved → user (prompts satisfaction survey)
// ════════════════════════════════════════════════════════════════

export async function sendTicketResolvedToUser(params: {
  ticket: SupportTicket
  userName: string
  resolutionNotes?: string | null
}): Promise<SendResult> {
  const { ticket, userName, resolutionNotes } = params
  const url = `${appUrl()}/support/tickets/${ticket.id}?rate=1`
  const subject = `Your ticket ${ticket.ticketNumber} has been resolved`
  const body = `
    <p>Hi ${escapeHtml(userName || 'there')},</p>
    <p>Your ticket <strong>${ticket.ticketNumber}</strong> has been marked resolved.</p>
    ${
      resolutionNotes
        ? `<p><strong>Resolution:</strong></p><div class="quote">${escapeHtml(resolutionNotes)}</div>`
        : ''
    }
    <p>How did we do? Your feedback helps us improve.</p>
    <p><a class="button" href="${url}">Rate this experience</a></p>
    <p style="color: #6b7280; font-size: 13px;">If the issue isn't actually resolved, reply on the ticket and we'll reopen it.</p>
  `
  const text = `Hi ${userName || 'there'},

Your ticket ${ticket.ticketNumber} is resolved.${resolutionNotes ? `\n\nResolution: ${resolutionNotes}` : ''}

Rate this experience: ${url}`
  return send({
    to: ticket.userEmail,
    subject,
    html: emailShell(`Ticket ${ticket.ticketNumber} resolved`, body),
    text,
    replyTo: ADMIN_INBOX,
  })
}

// ════════════════════════════════════════════════════════════════
// 6. Chat → ticket escalation → admin inbox
// ════════════════════════════════════════════════════════════════

type ChatEscalationMessage = { role: 'user' | 'assistant'; content: string }

export async function sendChatEscalationToAdmin(params: {
  ticket: SupportTicket
  userName: string
  conversationId: string
  totalMessages: number
  recentMessages: ChatEscalationMessage[]
}): Promise<SendResult> {
  const { ticket, userName, conversationId, totalMessages, recentMessages } = params
  const url = `${appUrl()}/admin/support/tickets/${ticket.id}`
  const subject = `[${ticket.ticketNumber}] Chat escalated to ticket`

  const transcriptHtml = recentMessages
    .slice(-5)
    .map(
      (m) => `
        <div class="quote" style="${m.role === 'user' ? '' : 'border-left-color: #4f46e5;'}">
          <div style="font-size:10px;text-transform:uppercase;color:#9ca3af;letter-spacing:0.04em;margin-bottom:2px;">
            ${m.role === 'user' ? escapeHtml(userName) || 'User' : 'AI assistant'}
          </div>
          ${escapeHtml(m.content)}
        </div>`
    )
    .join('')

  const transcriptText = recentMessages
    .slice(-5)
    .map((m) => `${m.role === 'user' ? userName || 'User' : 'AI'}: ${m.content}`)
    .join('\n\n')

  const body = `
    <p>The AI chatbot could not resolve this query — it has been escalated to a support ticket.</p>
    <div class="meta">
      <p><strong>Ticket:</strong> ${ticket.ticketNumber}</p>
      <p><strong>From:</strong> ${escapeHtml(userName)} (${escapeHtml(ticket.userEmail)})</p>
      <p><strong>Role:</strong> ${escapeHtml(ticket.userRole)}</p>
      <p><strong>Category:</strong> ${escapeHtml(ticket.category)} ${priorityBadge(ticket.priority)}</p>
      <p><strong>Total chat messages:</strong> ${totalMessages}</p>
    </div>
    <p><strong>Last messages of the conversation:</strong></p>
    ${transcriptHtml}
    <p><a class="button" href="${url}">Open ticket in admin</a></p>
    <p style="color:#6b7280;font-size:12px;">Conversation ID: <span style="font-family:monospace;">${conversationId}</span></p>
  `
  const text = `AI chatbot escalation → ticket ${ticket.ticketNumber}
From: ${userName} (${ticket.userEmail}) — ${ticket.userRole}
Category: ${ticket.category}  Priority: ${ticket.priority}
Total chat messages: ${totalMessages}

Last messages:
${transcriptText}

Open ticket: ${url}`
  return send({ to: ADMIN_INBOX, subject, html: emailShell('Chat escalated', body), text })
}

// ════════════════════════════════════════════════════════════════
// 7. Daily reminder digest → admin inbox
// ════════════════════════════════════════════════════════════════

export type StaleTicketRow = {
  ticketNumber: string
  ticketId: string
  subject: string
  userEmail: string
  userRole: string
  priority: SupportTicket['priority']
  ageHours: number
  reason: 'needs_first_response' | 'needs_followup'
}

export async function sendTicketReminderDigest(params: {
  needsFirstResponse: StaleTicketRow[]
  needsFollowup: StaleTicketRow[]
}): Promise<SendResult> {
  const { needsFirstResponse, needsFollowup } = params
  const total = needsFirstResponse.length + needsFollowup.length
  if (total === 0) return { success: true }

  const subject = `Support alert: ${total} ticket${total === 1 ? '' : 's'} need attention`
  const url = `${appUrl()}/admin/support`

  const renderRows = (rows: StaleTicketRow[]) =>
    rows
      .map((r) => {
        const ticketUrl = `${appUrl()}/admin/support/tickets/${r.ticketId}`
        return `
          <tr>
            <td style="padding:6px 8px;border-bottom:1px solid #e5e7eb;font-family:monospace;font-size:11px;">
              <a href="${ticketUrl}" style="color:#4f46e5;text-decoration:none;">${r.ticketNumber}</a>
            </td>
            <td style="padding:6px 8px;border-bottom:1px solid #e5e7eb;font-size:13px;">
              ${escapeHtml(truncate(r.subject, 60))}
            </td>
            <td style="padding:6px 8px;border-bottom:1px solid #e5e7eb;font-size:12px;color:#6b7280;">
              ${escapeHtml(r.userEmail)}<br/>
              <span style="font-size:10px;text-transform:uppercase;">${escapeHtml(r.userRole)}</span>
            </td>
            <td style="padding:6px 8px;border-bottom:1px solid #e5e7eb;">${priorityBadge(r.priority)}</td>
            <td style="padding:6px 8px;border-bottom:1px solid #e5e7eb;font-size:12px;">
              ${r.ageHours < 48 ? `${Math.round(r.ageHours)}h` : `${Math.round(r.ageHours / 24)}d`}
            </td>
          </tr>`
      })
      .join('')

  const table = (rows: StaleTicketRow[], heading: string) => `
    <h3 style="font-size:14px;margin:18px 0 6px;">${heading} (${rows.length})</h3>
    <table style="width:100%;border-collapse:collapse;">
      <thead>
        <tr style="background:#f9fafb;text-align:left;">
          <th style="padding:6px 8px;font-size:11px;color:#6b7280;">Ticket</th>
          <th style="padding:6px 8px;font-size:11px;color:#6b7280;">Subject</th>
          <th style="padding:6px 8px;font-size:11px;color:#6b7280;">User</th>
          <th style="padding:6px 8px;font-size:11px;color:#6b7280;">Priority</th>
          <th style="padding:6px 8px;font-size:11px;color:#6b7280;">Age</th>
        </tr>
      </thead>
      <tbody>${renderRows(rows)}</tbody>
    </table>
  `

  const body = `
    <p>${total} ticket${total === 1 ? '' : 's'} need${total === 1 ? 's' : ''} attention.</p>
    ${needsFirstResponse.length ? table(needsFirstResponse, 'Need first response (open >48h, no admin reply)') : ''}
    ${needsFollowup.length ? table(needsFollowup, 'Need follow-up (in progress, no admin reply >24h)') : ''}
    <p style="margin-top:18px;"><a class="button" href="${url}">Open support dashboard</a></p>
  `
  const text =
    `${total} ticket(s) need attention\n\n` +
    (needsFirstResponse.length
      ? `Need first response:\n` +
        needsFirstResponse.map((r) => `  ${r.ticketNumber} (${Math.round(r.ageHours)}h) — ${r.subject}`).join('\n') +
        '\n\n'
      : '') +
    (needsFollowup.length
      ? `Need follow-up:\n` +
        needsFollowup.map((r) => `  ${r.ticketNumber} (${Math.round(r.ageHours)}h) — ${r.subject}`).join('\n') +
        '\n\n'
      : '') +
    `Dashboard: ${url}`

  return send({ to: ADMIN_INBOX, subject, html: emailShell('Support alert', body), text })
}
